/**
 * Deterministic generator: reads src/design-tokens.json (the single canonical
 * source — SOT for the values themselves is references/source-docs/ADR-SYSTEM.md,
 * see design-system/00_GOVERNANCE/TRACEABILITY.md) and writes every derived
 * format into dist/. Never hand-edit dist/* — edit design-tokens.json and
 * re-run `pnpm --filter @executar/design-tokens build`.
 *
 * This replaces the one-off Python scripts used to produce the Phase 1
 * design-system/tokens/* snapshot with a real, repeatable, testable build.
 */
import { mkdirSync, writeFileSync, readFileSync, readdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";
import ts from "typescript";
import type { DesignTokens, TokenValue } from "./types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, "design-tokens.json");
const DIST = join(__dirname, "..", "dist");
const STYLES_SRC = join(__dirname, "styles");
const STYLES_DIST = join(DIST, "styles");

function loadTokens(): DesignTokens {
  return JSON.parse(readFileSync(SRC, "utf-8"));
}

function refToVar(ref: string): string {
  // "{color.palette.green.9}" -> "var(--color-green-9)"
  const inner = ref.slice(1, -1);
  const parts = inner.split(".");
  if (parts[0] === "color" && parts[1] === "palette") {
    return `var(--color-${parts[2]}-${parts[3]})`;
  }
  return `var(--${parts.join("-")})`;
}

function resolveRef(tokens: DesignTokens, ref: string): string {
  const inner = ref.slice(1, -1).split(".");
  if (inner[0] === "color" && inner[1] === "palette") {
    return tokens.color.palette[inner[2]][inner[3]].$value;
  }
  throw new Error(`Cannot resolve token reference: ${ref}`);
}

function buildVariablesCss(tokens: DesignTokens): string {
  const lines: string[] = [
    "/* AUTO-GENERATED by packages/design-tokens/src/build.ts — do not hand-edit. */",
    "/* SOT: references/source-docs/ADR-SYSTEM.md (Accepted). See design-system/00_GOVERNANCE/TRACEABILITY.md. */",
    ":root {",
  ];
  for (const [fam, steps] of Object.entries(tokens.color.palette)) {
    for (const [step, obj] of Object.entries(steps)) {
      lines.push(`  --color-${fam}-${step}: ${obj.$value};`);
    }
  }
  lines.push("");
  const simpleGroups: [Record<string, TokenValue<string>>, string][] = [
    [tokens.fontSize, "font-size"],
    [tokens.lineHeight, "line-height"],
    [tokens.letterSpacing, "letter-spacing"],
    [tokens.space, "space"],
    [tokens.radius, "radius"],
    [tokens.border.width, "border-width"],
    [tokens.shadow, "shadow"],
    [tokens.breakpoint, "breakpoint"],
    [tokens.container, "container"],
  ];
  for (const [group, prefix] of simpleGroups) {
    for (const [name, obj] of Object.entries(group)) {
      const key = name.replace(/\./g, "_");
      lines.push(`  --${prefix}-${key}: ${obj.$value};`);
    }
  }
  for (const [name, obj] of Object.entries(tokens.fontWeight)) {
    lines.push(`  --font-weight-${name}: ${obj.$value};`);
  }
  lines.push(`  --font-family-sans: ${tokens.font.family.sans.$value.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ")};`);
  lines.push(`  --font-family-mono: ${tokens.font.family.mono.$value.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ")};`);
  for (const [name, obj] of Object.entries(tokens.opacity)) {
    lines.push(`  --opacity-${name}: ${obj.$value};`);
  }
  for (const [name, obj] of Object.entries(tokens.grid)) {
    lines.push(`  --grid-${name}: ${obj.$value};`);
  }
  for (const [name, obj] of Object.entries(tokens.motion.duration)) {
    lines.push(`  --motion-duration-${name}: ${obj.$value};`);
  }
  const bez = tokens.motion.easing.out.$value;
  lines.push(`  --motion-easing-out: cubic-bezier(${bez.join(", ")});`);
  for (const [name, obj] of Object.entries(tokens.zIndex)) {
    lines.push(`  --z-${name}: ${obj.$value};`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

function buildThemeCss(tokens: DesignTokens): string {
  const lines: string[] = [
    "/* AUTO-GENERATED semantic theme layer. Consumes variables.css. */",
    '@import "./variables.css";',
    "",
    ":root, [data-theme='light'] {",
  ];
  for (const [group, items] of Object.entries(tokens.color.semantic)) {
    for (const [name, obj] of Object.entries(items)) {
      const val = obj.$value;
      const cssVal = val.startsWith("{") ? refToVar(val) : val;
      lines.push(`  --semantic-${group}-${name}: ${cssVal};`);
    }
  }
  lines.push("}");
  lines.push("");
  lines.push("/* Dark theme: alias remap only — not yet accessibility-audited, see ACCESSIBILITY.md. */");
  lines.push("[data-theme='dark'] {");
  lines.push("  --semantic-background-canvas: var(--color-neutral-12);");
  lines.push("  --semantic-background-surface: var(--color-neutral-11);");
  lines.push("  --semantic-background-elevated: var(--color-neutral-10);");
  lines.push("  --semantic-text-primary: var(--color-neutral-1);");
  lines.push("  --semantic-text-secondary: var(--color-neutral-4);");
  lines.push("  --semantic-text-muted: var(--color-neutral-6);");
  lines.push("  --semantic-text-on_brand: var(--color-neutral-1);");
  lines.push("  --semantic-text-link: var(--color-azure-7);");
  lines.push("  --semantic-border-subtle: var(--color-neutral-10);");
  lines.push("  --semantic-border-default: var(--color-neutral-9);");
  lines.push("  --semantic-border-strong: var(--color-neutral-7);");
  lines.push("  --semantic-action-primary: var(--color-green-8);");
  lines.push("  --semantic-action-primary_hover: var(--color-green-7);");
  lines.push("  --semantic-action-secondary: var(--color-azure-8);");
  lines.push("  --semantic-state-success_text: var(--color-green-7);");
  lines.push("  --semantic-state-info_text: var(--color-azure-7);");
  lines.push("  --semantic-state-warning_text: var(--color-warning-7);");
  lines.push("  --semantic-state-error_text: var(--color-error-7);");
  lines.push("}");
  lines.push("");
  lines.push("/* High-contrast theme (WCAG AAA-leaning): reinforced pairs. RECOMMENDED — not audited yet. */");
  lines.push("[data-theme='high-contrast'] {");
  lines.push("  --semantic-text-primary: var(--color-neutral-12);");
  lines.push("  --semantic-background-canvas: var(--color-neutral-1);");
  lines.push("  --semantic-border-default: var(--color-neutral-12);");
  lines.push("  --semantic-action-primary: var(--color-green-11);");
  lines.push("  --semantic-action-secondary: var(--color-azure-11);");
  lines.push("}");
  return lines.join("\n") + "\n";
}

function buildTokensNativeTs(tokens: DesignTokens): string {
  const ts: string[] = [
    "// AUTO-GENERATED by packages/design-tokens/src/build.ts. Consumed by apps/app (Expo + React Native + Tamagui).",
    "// Do not hand-edit — edit ../src/design-tokens.json and re-run the build.",
    "",
    "export const palette = {",
  ];
  for (const [fam, steps] of Object.entries(tokens.color.palette)) {
    ts.push(`  ${fam}: {`);
    for (const [step, obj] of Object.entries(steps)) {
      ts.push(`    "${step}": "${obj.$value}",`);
    }
    ts.push("  },");
  }
  ts.push("} as const;\n");

  ts.push("export const space = {");
  for (const [name, obj] of Object.entries(tokens.space)) {
    const key = name.replace(/\./g, "_");
    ts.push(`  "${key}": ${parseFloat(obj.$value)},`);
  }
  ts.push("} as const;\n");

  ts.push("export const radius = {");
  for (const [name, obj] of Object.entries(tokens.radius)) {
    ts.push(`  ${name}: ${parseFloat(obj.$value)},`);
  }
  ts.push("} as const;\n");

  ts.push("export const fontSize = {");
  for (const [name, obj] of Object.entries(tokens.fontSize)) {
    ts.push(`  "${name.replace(/-/g, "_")}": ${parseFloat(obj.$value)},`);
  }
  ts.push("} as const;\n");

  ts.push("export const lineHeight = {");
  for (const [name, obj] of Object.entries(tokens.lineHeight)) {
    ts.push(`  "${name.replace(/-/g, "_")}": ${parseFloat(obj.$value)},`);
  }
  ts.push("} as const;\n");

  ts.push("export const fontWeight = {");
  for (const [name, obj] of Object.entries(tokens.fontWeight)) {
    ts.push(`  "${name.replace(/-/g, "_")}": ${obj.$value},`);
  }
  ts.push("} as const;\n");

  ts.push("export const motion = {");
  ts.push("  duration: {");
  for (const [name, obj] of Object.entries(tokens.motion.duration)) {
    ts.push(`    ${name}: ${parseFloat(obj.$value)},`);
  }
  ts.push("  },");
  ts.push(`  easingOut: [${tokens.motion.easing.out.$value.join(", ")}] as [number, number, number, number],`);
  ts.push("} as const;\n");

  ts.push("export const semanticLight: Record<string, string> = {");
  for (const [group, items] of Object.entries(tokens.color.semantic)) {
    for (const [name, obj] of Object.entries(items)) {
      const val = obj.$value;
      const resolved = val.startsWith("{") ? resolveRef(tokens, val) : val;
      ts.push(`  "${group}_${name}": "${resolved}",`);
    }
  }
  ts.push("};\n");

  return ts.join("\n") + "\n";
}

function main() {
  const tokens = loadTokens();
  mkdirSync(DIST, { recursive: true });

  writeFileSync(join(DIST, "variables.css"), buildVariablesCss(tokens));
  writeFileSync(join(DIST, "theme.css"), buildThemeCss(tokens));
  const tokensNativeSource = buildTokensNativeTs(tokens);
  writeFileSync(join(DIST, "tokens.native.ts"), tokensNativeSource);
  // package.json's "./tokens.native" export points at dist/tokens.native.js
  // (declared alongside dist/tokens.native.d.ts, written further down) — this
  // was missing for a while: nothing consumed apps/app/tamagui.config.ts's
  // `@executar/design-tokens/tokens.native` import until Phase 2C.3 actually
  // bundled it (`expo export`), which is when "could not be found" surfaced.
  // Metro/webpack/Vite all need a real .js file, not just the .ts source
  // dist/tokens.native.ts is kept as above for readability/diffing.
  const { outputText } = ts.transpileModule(tokensNativeSource, {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
  });
  writeFileSync(join(DIST, "tokens.native.js"), outputText);
  writeFileSync(join(DIST, "design-tokens.yaml"), yaml.dump(tokens, { noRefs: true, lineWidth: 100 }));
  writeFileSync(join(DIST, "design-tokens.json"), JSON.stringify(tokens, null, 2));

  // Static, hand-authored stylesheets (reset/typography/layout/utilities) —
  // copied verbatim from design-system/styles/, not generated from tokens,
  // but shipped from this package so apps don't need to reach into
  // design-system/ (the documentation snapshot) at runtime.
  mkdirSync(STYLES_DIST, { recursive: true });
  for (const file of readdirSync(STYLES_SRC)) {
    copyFileSync(join(STYLES_SRC, file), join(STYLES_DIST, file));
  }

  // index.js/.d.ts (the typed runtime API, including contrast.ts) is compiled
  // separately by `tsc -p tsconfig.build.json` — see the "build" script in
  // package.json. It must run AFTER this script, since it emits
  // dist/index.js with a relative `./design-tokens.json` import that resolves
  // to the dist/design-tokens.json written above.

  // Compile tokens.native.ts to .js/.d.ts too, so it's consumable without a TS build step downstream.
  writeFileSync(
    join(DIST, "tokens.native.d.ts"),
    `export declare const palette: Record<string, Record<string, string>>;\nexport declare const space: Record<string, number>;\nexport declare const radius: Record<string, number>;\nexport declare const fontSize: Record<string, number>;\nexport declare const lineHeight: Record<string, number>;\nexport declare const fontWeight: Record<string, number>;\nexport declare const motion: { duration: Record<string, number>; easingOut: [number, number, number, number] };\nexport declare const semanticLight: Record<string, string>;\n`
  );

  console.log(`Built design tokens -> ${DIST}`);
}

main();
